# Generated by Django 5.2.6 on 2025-09-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('JERSEY', 'Jersey'), ('BOOTS', 'Boots'), ('BALL', 'Ball'), ('ACCESSORY', 'Accessory'), ('TICKET', 'Match Ticket')], default='JERSEY', max_length=20),
        ),
    ]
